# This is a basic workflow to help you get started with Actions

name: doh-update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # install ipcalc-ng
      - name: Install ipcalc-ng
        run: sudo apt-get install -y ipcalc-ng
        
      # Runs a single command using the runners shell
      - name: Run DoH lookup
        run: sh ./doh-lookup.sh

      # Runs a set of commands using the runners shell
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Commit message
          commit_message: automatic/regular ip address updates
          # File pattern used for `git add`. For example `src/*.js`
          file_pattern: ./doh-ipv*.txt ./doh-domains.txt ./doh-domains_abandoned.txt
